### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by leppaott**

### CODE REVIEW

**Review by veituomi — APPROVED** [review]
Nice version numbers! Solid gold.

**Review by pullari — APPROVED** [review]

**Review by madkoppa — APPROVED** [review]
Very good.

**Comment by henniska** [comment]
gj

**Review by henniska — APPROVED** [review]

**Review by jope25 — APPROVED** [review]
Noice

**Review by jope25 — APPROVED** [review]

**Pull request merged**
